version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    timezone: Asia/Tokyo
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    timezone: Asia/Tokyo
