version: 1
update_configs:
  # Keep poetry.lock up to date weekly
  # PR will be merged automatically
  - package_manager: "python"
    directory: "/"
    update_schedule: "weekly"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
