name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      POETRY_VER: 1.0.5

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        # install curl
        sudo apt-get install -y gettext
        # install poetry
        wget https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py
        python get-poetry.py --version $POETRY_VER
        # install dependent PyPI packages
        poetry install
        echo "::set-env name=PATH::$HOME/.poetry/bin:$PATH"
        ls -al $HOME/.poetry/bin
    - name: Build
      run: |
        echo $PATH
        poetry run sphinx-build -M html source build -W
        poetry run sphinx-build -M html source build -D language=ja -W
    - name: Test
      run: |
        STATISTICS_CMD="msgfmt -o /dev/null source/locales/ja/LC_MESSAGES/*.po -v --statistics"
        # Fail and show result if statistics of translation file include messages after 'translated messages'.
        #   invalid ex. source/locales/ja/LC_MESSAGES/index.po: 4 translated messages, 1 fuzzy translation, 1 untranslated message.
        $STATISTICS_CMD 2>&1 | grep -v -q ' translated messages, *' || ($STATISTICS_CMD && false)
