name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      python-version: 3.7

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv sync --dev
    - name: Build
      run: |
        pipenv run build -W
        pipenv run build_ja -W
