name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      POETRY_VER: 2.0.1

    steps:
    - uses: actions/checkout@v4
    - name: Install poetry
      run: pipx install poetry==$POETRY_VER
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: 3.10
        cache: 'poetry'
    - name: Install tools
      run: |
        # install curl
        sudo apt-get install -y gettext
    - name: Install dependencies
      run: |
        poetry install
    - name: Build
      run: |
        poetry run sphinx-build -M html source build -W
        poetry run sphinx-build -M html source build -D language=ja -W
    - name: Test
      run: |
        STATISTICS_CMD="msgfmt -o /dev/null source/locales/ja/LC_MESSAGES/*.po -v --statistics"
        # Fail and show result if statistics of translation file include messages after 'translated messages'.
        #   invalid ex. source/locales/ja/LC_MESSAGES/index.po: 4 translated messages, 1 fuzzy translation, 1 untranslated message.
        $STATISTICS_CMD 2>&1 | grep -v -q ' translated messages, *' || ($STATISTICS_CMD && false)
