name: Playwright Tests
on:
  push:
    branches: [ main, master, support/add-visual-regression-test ]

  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    # container:
    #   # Match the Playwright version
    #   # https://github.com/microsoft/playwright/issues/20010
    #   image: mcr.microsoft.com/playwright:v1.50.1-jammy
    env:
      POETRY_VER: "2.0.1"
    steps:
    - uses: actions/checkout@v4

    # PyPI
    - name: Install poetry
      run: pipx install poetry==$POETRY_VER
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: "poetry"
    - name: Install tools
      run: |
        # install curl
        sudo apt-get install -y gettext
    - run: poetry install --all-groups

    # npm
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - run: yarn install
    - name: Install dependencies
      run: yarn pretest:install-playwright
    - name: Run Playwright tests
      run: yarn test:vrt
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
