name: Update Screenshots
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      update-screenshots:
        type: boolean
        default: false
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ${{ github.repository }}/.github/workflows/exec_playwright@master
    - name: Cache VRT snapshots
      uses: actions/cache@v4
      id: vrt-cache
      with:
        path: playwright-report
        key: vrt-${{ vars.RECENT_ARTIFACTS_SHA256 }}
