name: Update Screenshots
on:
  push:
    branches: [ main, master, support/add-visual-regression-test ]
  workflow_dispatch:
    inputs:
      update-screenshots:
        type: boolean
        default: false
jobs:
  update-vrt-screenshots:
    uses: ryu-sato/sphinx-doc-sample/.github/workflows/reusable_exec_playwright.yml@support/add-visual-regression-test
    with:
      git_ref: ${{ github.sha }}
      update_screenshots: true
