name: Visual Regression Test
on:
  push:
    branches: [ main, master, support/add-visual-regression-test ]
  pull_request:
    branches: [ main, master ]
jobs:
  vrt:
    timeout-minutes: 60
    uses: ryu-sato/sphinx-doc-sample/.github/workflows/reusable_exec_playwright.yml@support/add-visual-regression-test
