name: Visual Regression Test
on:
  push:
    branches: [ main, master, support/add-visual-regression-test ]
  pull_request:
    branches: [ main, master ]
jobs:
  load_master_screenshots:
    env:
      TEST_RESULT_DIR: test-results
    outputs:
      needs_master_screenshots_cache: ${{ steps.load_master_screenshots_from_cache.outputs.cache-hit == 'false' }}
    steps:
    - name: Load master screenshots from cache
      id: load_master_screenshots_from_cache
      uses: actions/cache@v4
      with:
        path: ${{ env.TEST_RESULT_DIR }}
        key: playwright-result-${{ github.sha }}
  update_master_screenshots:
    needs: load_master_screenshots
    if: needs.load_master_screenshots.outputs.needs_master_screenshots_cache
    uses: ryu-sato/sphinx-doc-sample/.github/workflows/reusable_exec_playwright.yml@support/add-visual-regression-test
  vrt:
    needs:
    - load_master_screenshots
    - update_master_screenshots
    uses: ryu-sato/sphinx-doc-sample/.github/workflows/reusable_exec_playwright.yml@support/add-visual-regression-test
    with:
      git_ref: ${{ github.sha }}
