name: Visual Regression Test
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  vrt:
    timeout-minutes: 60
    uses: ryu-sato/sphinx-doc-sample/.github/workflows/exec_playwright@support/add-visual-regression-test
