name: Visual Regression Test
on:
  push:
    branches: [ main, master, support/add-visual-regression-test ]
  pull_request:
    branches: [ main, master ]
jobs:
  load_master_screenshots:
    runs-on: ubuntu-latest
    env:
      TEST_RESULT_DIR: test-results
    outputs:
      master_screenshots_cache_hit: ${{ steps.load_master_screenshots_from_cache.outputs.cache-hit }}
    steps:
    - name: Load master screenshots from cache
      id: load_master_screenshots_from_cache
      uses: actions/cache@v4
      with:
        path: ${{ env.TEST_RESULT_DIR }}
        key: ${{ env.TEST_RESULT_DIR }}-master
  update_master_screenshots:
    needs: load_master_screenshots
    if: needs.load_master_screenshots.outputs.master_screenshots_cache_hit == 'false'
    uses: ryu-sato/sphinx-doc-sample/.github/workflows/reusable_exec_playwright.yml@support/add-visual-regression-test
    with:
      expected_screenshots_cache_key_base: master
      update_screenshots: true

  vrt:
    needs:
    - load_master_screenshots
    - update_master_screenshots
    if: |
      always() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled')
    uses: ryu-sato/sphinx-doc-sample/.github/workflows/reusable_exec_playwright.yml@support/add-visual-regression-test
    with:
      expected_screenshots_cache_key_base: master
